#!/bin/bash

echo "🔧 Quick fix for language system..."

# Language selector HTML to insert
LANGUAGE_SELECTOR_HTML='                    <div class="language-selector relative">
                        <button id="languageBtn" class="flex items-center space-x-2 px-3 py-2 rounded-lg bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                            <span id="currentLanguageFlag">🇺🇸</span>
                            <span id="currentLanguageName" class="hidden md:inline">English</span>
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                            </svg>
                        </button>
                        <div id="languageDropdown" class="absolute right-0 mt-2 w-64 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 hidden z-50 max-h-96 overflow-y-auto">
                            <div class="p-2">
                                <input type="text" id="languageSearch" placeholder="Search languages..." class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg mb-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300">
                                <div id="languageList" class="space-y-1">
                                    <!-- Language options will be generated by JavaScript -->
                                </div>
                            </div>
                        </div>
                    </div>'

# Language initialization script
LANGUAGE_INIT_SCRIPT='            // Initialize language system
            if (window.languageSelector) {
                window.languageSelector.init();
            }'

# List of key pages to fix
PAGES=(
    "vegetable-biryani.html"
    "quinoa-bowl.html"
    "mediterranean-salad.html"
    "lentil-soup.html"
    "idli-sambar.html"
    "dosa-chutney.html"
    "upma.html"
    "vegetable-pulao.html"
    "vegetable-stir-fry.html"
    "mushroom-risotto.html"
    "avocado-toast.html"
    "greek-yogurt-parfait.html"
    "chia-pudding.html"
    "super-green-smoothie.html"
    "golden-turmeric-latte.html"
    "tofu-scramble.html"
    "black-bean-tacos.html"
    "grilled-salmon.html"
    "quinoa-stuffed-bell-peppers.html"
    "sweet-potato-buddha-bowl.html"
    "tofu-stir-fry.html"
    "millet-khichdi.html"
    "rainbow-buddha-bowl.html"
    "quinoa-buddha-bowl.html"
    "vegetable-poha.html"
    "vegetable-pasta.html"
    "vegetable-soup.html"
    "avocado-mousse.html"
    "veggie-stir-fry.html"
    "diet-planner.html"
    "games.html"
    "recipes.html"
)

for page in "${PAGES[@]}"; do
    if [ -f "$page" ]; then
        echo "📝 Fixing $page..."
        
        # Replace the language selector placeholder with actual HTML
        sed -i '' 's|<!-- Language Selector will be inserted here by JavaScript -->|'"$LANGUAGE_SELECTOR_HTML"'|g' "$page"
        
        # Add language initialization script
        sed -i '' 's|loadComments();|loadComments();\n'"$LANGUAGE_INIT_SCRIPT"';|g' "$page"
        
        # Also add to DOMContentLoaded if it exists
        sed -i '' 's|document\.addEventListener('\''DOMContentLoaded'\'', function() {|document.addEventListener('\''DOMContentLoaded'\'', function() {\n'"$LANGUAGE_INIT_SCRIPT"';|g' "$page"
        
        echo "✅ Fixed $page"
    else
        echo "⚠️  File not found: $page"
    fi
done

echo "🎉 Quick fix completed!" 